import { MD3LightTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#AE1131',
    primaryContainer: '#FFDAD6',
    secondary: '#AE1131',
    secondaryContainer: '#FFDAD6',
    tertiary: '#AE1131',
    tertiaryContainer: '#FFDAD6',
    surface: '#FFFBFE',
    surfaceVariant: '#F3DFD1',
    background: '#FFFBFE',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#410002',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#410002',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#410002',
    onSurface: '#1C1B1F',
    onSurfaceVariant: '#52443D',
    onBackground: '#1C1B1F',
    onError: '#FFFFFF',
    onErrorContainer: '#410002',
    outline: '#85746F',
    outlineVariant: '#D7C3BC',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#313033',
    inverseOnSurface: '#F4EFF4',
    inversePrimary: '#FFB4A8',
    elevation: {
      level0: 'transparent',
      level1: '#FFF8F6',
      level2: '#FFF2F0',
      level3: '#FFEDEA',
      level4: '#FFEBE8',
      level5: '#FFE8E4',
    },
  },
}; 